version: "3"
services:
  mariadb:
    image: mariadb
    ports: 
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: devpass      
      MARIADB_PASSWORD: devpass
      MARIADB_USER: dev
      MARIADB_DATABASE: ums
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - ums-back-office
  ums-frontend:
    image: ums-frontend
    build: ./frontend
    networks:
      - ums-user-facing
  ums-backend:
    image: ums-backend
    build: ./backend
    depends_on: 
      - mariadb
    environment:
      UMS_DB_NAME: ums
      UMS_DB_USERNAME: dev
      UMS_DB_PASSWORD: devpass
      UMS_DB_PORT: 3306
      UMS_DB_IP: mariadb
    networks: 
      - ums-user-facing
      - ums-back-office
  ums-proxy:
    image: nginx:1.21
    ports:
      - 7887:80
    depends_on:
      - ums-frontend
      - ums-backend
    volumes:
      - "./proxy/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - ums-user-facing
volumes:
  mariadb:
    driver: local
networks:
  ums-user-facing:
  ums-back-office: